CREATE DATABASE IF NOT EXISTS nanda_diagnosticos;
USE nanda_diagnosticos;

CREATE TABLE IF NOT EXISTS diagnosticos (
    id INT PRIMARY KEY AUTO_INCREMENT,
    codigo VARCHAR(10),
    nombre VARCHAR(255),
    sintomas TEXT,
    intervenciones_nic TEXT,
    resultados_noc TEXT
);

INSERT INTO diagnosticos (codigo, nombre, sintomas, intervenciones_nic, resultados_noc) VALUES
('00292', 'Disposición para mejorar la autogestión de la salud', 'interés en aprender,voluntad de cambiar hábitos,confianza en las habilidades,preocupación por el bienestar', 'Fomentar la autoeducación sobre la autogestión.,Establecer metas de salud específicas y alcanzables.,Brindar recursos educativos sobre autocuidado.,Proporcionar apoyo continuo para motivar la autogestión.', 'Autogestión de la salud,Conocimiento sobre la salud'),
('00162', 'Disposición para mejorar el estilo de vida', 'reconocimiento de malos hábitos,deseo de mejorar la calidad de vida,falta de energía,estrés o ansiedad', 'Proponer un plan de acción gradual para cambiar hábitos poco saludables.,Fomentar la educación sobre nutrición y ejercicio.,Ayudar a establecer metas alcanzables en términos de actividad física y dieta.,Proporcionar seguimiento y ajustes según el progreso del paciente.', 'Mejora de la salud,Autocuidado'),
('00161', 'Disposición para mejorar el conocimiento', 'búsqueda activa de información,actitud abierta hacia nuevas ideas,aceptación de nuevas prácticas de salud', 'Proporcionar materiales educativos accesibles y comprensibles.,Organizar talleres interactivos para mejorar la comprensión sobre la salud.,Fomentar la participación en grupos educativos de salud.,Evaluar la comprensión del paciente y ajustar las intervenciones educativas.', 'Conocimiento sobre la salud,Participación en la educación para la salud'),
('00078', 'Manejo ineficaz de la salud', 'no adherencia a los regímenes terapéuticos,dificultad para reconocer cambios en el estado de salud,desorganización en el manejo de condiciones crónicas', 'Proporcionar educación continua sobre la importancia del tratamiento.,Establecer un plan de seguimiento para el manejo de la salud.,Asegurar que el paciente comprenda y se adhiera a su plan de tratamiento.,Brindar apoyo emocional y motivacional para el autocuidado.', 'Manejo de la salud,Autogestión de la salud'),
('00162', 'Conducta de búsqueda de salud ineficaz', 'desconfianza en los servicios de salud,evitar atención médica,falta de conocimiento sobre servicios de salud', 'Proveer información sobre los servicios de salud disponibles.,Brindar orientación sobre cómo acceder a atención médica de calidad.,Reforzar la importancia de la prevención y los exámenes regulares.,Guiar al paciente para que se sienta cómodo al buscar ayuda médica.', 'Acceso a la atención médica,Conocimiento sobre servicios de salud'),
('00168', 'Disposición para mejorar el manejo de la salud', 'deseo de mejorar las habilidades de autogestión,interés por cambiar conductas relacionadas con la salud,actitud positiva hacia el cambio', 'Fomentar la autoeficacia mediante el refuerzo positivo.,Establecer metas de salud alcanzables a corto y largo plazo.,Proponer intervenciones personalizadas para mejorar el manejo de la salud.,Proporcionar herramientas para el autocontrol de condiciones de salud.', 'Manejo de la salud,Autogestión de la salud'),
('00167', 'Autogestión ineficaz', 'desorganización en el manejo de la salud,dificultad para seguir pautas de autocuidado,falta de control sobre condiciones crónicas', 'Proponer un plan de autogestión individualizado.,Brindar formación continua sobre la autogestión.,Utilizar herramientas como recordatorios o aplicaciones de salud para seguimiento.,Proporcionar apoyo constante para mejorar la adherencia al tratamiento.', 'Autogestión de la salud,Conocimiento sobre la salud'),
('00244', 'Disposición para mejorar la autogestión', 'motivación para mejorar el control de la salud,actitud positiva hacia la adopción de hábitos saludables,interés en aprender sobre la autogestión', 'Fomentar la reflexión sobre las metas de autogestión de salud.,Proponer estrategias y metas a corto y largo plazo.,Establecer un plan detallado para la mejora de la autogestión.,Reforzar el empoderamiento del paciente con la toma de decisiones.', 'Autogestión de la salud,Conocimiento sobre la salud'),
('00179', 'Autogestión ineficaz de la diabetes', 'descontrol en los niveles de glucosa,dificultad para seguir el régimen de medicación o dieta,desconocimiento de las complicaciones de la diabetes', 'Brindar educación sobre la diabetes y su manejo.,Fomentar el control regular de los niveles de glucosa.,Proponer cambios en la dieta que favorezcan el control de la glucosa.,Ayudar al paciente a establecer un plan de ejercicio adecuado.', 'Manejo de la diabetes,Autogestión de la salud'),
('00001', 'Nutrición desequilibrada: más de lo que el cuerpo necesita', 'aumento de peso,obesidad,fatiga,hipertensión,dolor de cabeza', 'Proponer un plan de alimentación balanceado.,Fomentar la actividad física regular.,Monitorear el peso y la ingesta calórica.,Ofrecer educación sobre control de porciones y elección de alimentos saludables.', 'Equilibrio nutricional,Control de peso'),
('00002', 'Nutrición desequilibrada: menos de lo que el cuerpo necesita', 'pérdida de peso,desnutrición,fatiga extrema,mareos,falta de concentración', 'Aumentar la ingesta de alimentos ricos en nutrientes.,Proponer suplementos nutricionales.,Evaluar y tratar las deficiencias nutricionales.,Fomentar la hidratación adecuada.', 'Equilibrio nutricional,Ingesta de alimentos'),
('00163', 'Disposición para mejorar la nutrición', 'deseo de mejorar la dieta,actitud positiva hacia los cambios alimenticios,falta de apetito', 'Crear un plan nutricional personalizado.,Proveer recursos educativos sobre nutrición.,Monitorear la ingesta nutricional y ajustar el plan.,Establecer metas de nutrición a corto y largo plazo.', 'Equilibrio nutricional,Control de peso'),
('00134', 'Náuseas', 'sensación de malestar estomacal,ganas de vomitar,pérdida de apetito', 'Administrar medicamentos antieméticos.,Ofrecer líquidos claros y comidas suaves.,Evitar olores fuertes y alimentos irritantes.', 'Reducción de las náuseas,Confort gastrointestinal'),
('00255', 'Riesgo de náuseas', 'historia de náuseas recurrentes,uso de medicamentos que causan náuseas', 'Monitorear signos de náuseas.,Proponer una dieta ligera y evitar alimentos irritantes.,Administrar medicamentos preventivos.', 'Reducción de las náuseas,Confort gastrointestinal'),
('00013', 'Diarrea', 'evacuaciones líquidas,dolor abdominal,urgencia para defecar', 'Rehidratar al paciente.,Monitorear la frecuencia de evacuaciones.,Implementar una dieta baja en fibra y suave.', 'Equilibrio de líquidos,Confort gastrointestinal'),
('00196', 'Deterioro de la absorción gastrointestinal', 'pérdida de peso no explicada,deficiencias nutricionales,síntomas de desnutrición', 'Proporcionar suplementos nutricionales.,Evaluar la función gastrointestinal y el tratamiento.,Proponer cambios en la dieta para mejorar la absorción.', 'Absorción gastrointestinal,Estado nutricional'),
('00195', 'Riesgo de desequilibrio electrolítico', 'fatiga,debilidad muscular,cambios en la presión arterial', 'Monitorear los niveles de electrolitos.,Administrar suplementos de electrolitos.,Fomentar la hidratación adecuada.', 'Equilibrio de líquidos,Balance electrolítico'),
('00270', 'Riesgo de desequilibrio nutricional', 'dieta inadecuada,pérdida de peso,malnutrición', 'Implementar un plan nutricional adecuado.,Proporcionar educación sobre hábitos alimenticios saludables.,Monitorear la ingesta nutricional.', 'Equilibrio nutricional,Estado nutricional'),
('00020', 'Incontinencia urinaria de urgencia', 'urgencia para orinar,pérdida involuntaria de orina,frecuencia urinaria aumentada', 'Entrenamiento de la vejiga.,Uso de medicamentos anticolinérgicos.,Ejercicios de Kegel.', 'Control de la micción,Confort urinario'),
('00017', 'Incontinencia urinaria de esfuerzo', 'pérdida de orina al toser o reír,sensación de incomodidad durante el esfuerzo físico', 'Ejercicios de Kegel.,Uso de dispositivos absorbentes.,Terapia quirúrgica si es necesario.', 'Control de la micción,Confort urinario'),
('00015', 'Riesgo de deterioro de la eliminación urinaria', 'alteración en el patrón de micción,dificultad para vaciar completamente la vejiga', 'Monitorear la cantidad de orina y la función renal.,Fomentar el vaciamiento completo de la vejiga.,Ofrecer educación sobre la importancia de la hidratación.', 'Control de la micción,Confort urinario'),
('00011', 'Estreñimiento', 'defecación infrecuente,dolor abdominal,distensión,sensación de evacuación incompleta', 'Aumentar la ingesta de fibra y líquidos.,Fomentar la actividad física regular.,Administrar laxantes suaves si es necesario.', 'Eliminación fecal,Confort gastrointestinal'),
('00013', 'Diarrea', 'evacuaciones líquidas,dolor abdominal,urgencia para defecar', 'Rehidratar al paciente.,Administrar medicamentos antidiarreicos.,Implementar una dieta suave y baja en fibra.', 'Equilibrio de líquidos,Confort gastrointestinal'),
('00014', 'Incontinencia fecal', 'pérdida involuntaria de heces,incapacidad para controlar evacuaciones', 'Establecer una rutina de evacuación.,Administrar medicamentos para mejorar la consistencia de las heces.,Utilizar dispositivos absorbentes para control.', 'Control de la eliminación fecal,Confort gastrointestinal'),
('00030', 'Intercambio gaseoso deteriorado', 'dificultad para respirar,cianosis,fatiga', 'Administrar oxígeno suplementario.,Monitorear los niveles de oxígeno en sangre.,Fomentar técnicas de respiración controlada.', 'Intercambio gaseoso,Oxigenación'),
('00031', 'Limpieza ineficaz de las vías respiratorias', 'dificultad para expectorar,tos persistente,respiración ruidosa', 'Fomentar la tos productiva.,Administrar medicamentos mucolíticos.,Realizar fisioterapia respiratoria.', 'Eliminación de secreciones respiratorias,Capacidad respiratoria'),
('00039', 'Riesgo de aspiración', 'dificultad para tragar,historia de atragantamientos', 'Modificar la dieta a líquidos espesos o alimentos triturados.,Posicionar adecuadamente al paciente durante y después de comer.,Monitorear signos de aspiración durante la ingesta.', 'Riesgo de aspiración,Seguridad respiratoria');
